### ISSUE TITLE
Enhance readability of content

### ISSUE THREAD

**Issue by tomeara** [WGBH/bostonlocaltv#118]
As a user
In order to maximize usability and readability
When I view content
Then I should be able to read content with clean typography
And a positive aesthetic

**Done when**
- Blog posts have a line-height and size that matches the PSD
- A blog post should have a small top image that matches the PSD
- A post should match the PSD in general

**Does not include**
- Rails coding/administration for the posts and post images

**Comment by mccalluc** [comment]
We're now using cmless rather than wordpress, so there's not a lot of style, but it's consistent with the rest of the site. Closing.
