### ISSUE TITLE
Secret tokens shouldn't be in source control

### ISSUE THREAD

**Issue by seanlinsley** [WGBH/bostonlocaltv#172]
The secret tokens in [`config/initializers/secret_token.rb`](https://github.com/WGBH/bostonlocaltv/blob/4a7f5982c194d306f5b6786c70a67316d1a331cc/config/initializers/secret_token.rb#L7) and [`config/initializers/devise.rb`](https://github.com/WGBH/bostonlocaltv/blob/4a7f5982c194d306f5b6786c70a67316d1a331cc/config/initializers/devise.rb#L18) shouldn't be in source control, as it lets an attacker do all sorts of nasty stuff by manipulating user sessions.

There are many different approaches to fix this, but here's one for convenience: http://daniel.fone.net.nz/blog/2013/05/20/a-better-way-to-manage-the-rails-secret-token/

**Comment by mccalluc** [comment]
It looks like they are now being read from environment variables... and in any case we're moving to make the site stateless, so it really wouldn't matter if we were spoofed. Closing.
