### ISSUE TITLE
Upgrade deployment

### ISSUE THREAD

**Issue by afred** [WGBH/bostonlocaltv#183]
Currently using Capistrano 2.something.

Should at least upgrade to Capistrano 3 to avoid incurring too much tech debt.

Consider adopting the companion deployment repository pattern, similar to [aapb_deployment](https://atlas.wgbh.org/stash/projects/MLA/repos/aapb_deployment/browse)

**Comment by mccalluc** [comment]
https://github.com/WGBH/bostonlocaltv_deploy/ exists, and we've got the rails up. solr isn't running, yet, though.
