### ISSUE TITLE
Ingest?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/bostonlocaltv#184]
@afred, I'd like to see if we can get this deployed with the new machinery. Do you know how records get ingested into this, and where they come from?

**Comment by afred** [comment]
The data comes from a variety of FMP databases, initially maintained by @sroosa, but I don't know when was the last time she tinkered with them.

The FMP exports are translated to PBCore using [a handful of XSLT stylesheets](https://github.com/WGBH/bostonlocaltv_data_stylesheets). I have only ever used `xsltproc` to do the actual translations, but I assume you can use other tools as well.

Also, the PBCore will likely fail validation, but it is good enough for the [ingest scripts](https://github.com/WGBH/bostonlocaltv/tree/master/app/models/dataset). This whole process could use a refactor.

**Comment by mccalluc** [comment]
Ingest is working locally. Details to be worked out can be filed separately.
