### ISSUE TITLE
Remove vestigial Dataset classes

### ISSUE THREAD

**Issue by mccalluc** [WGBH/bostonlocaltv#194]
@sroosa / @afred : There are only 4 different sources that we are importing from, but in [`data.rake`](https://github.com/WGBH/bostonlocaltv/blob/master/lib/tasks/data.rake) and [`dataset/`](https://github.com/WGBH/bostonlocaltv/tree/master/app/models/dataset) we also have references to BPL and NHF. Are you aware of any ingests we would do that would hit this code? If not, I'd like to delete.

**Comment by sroosa** [comment]
@mccalluc There are only 4 databases that are sources of data for the website. We had more databases during the project, but none of the data in them is being ingested into or exposed on the site. I don't see why we would need ingest scripts for them.

**Comment by afred** [comment]
Those are relics from days of yore. I didn't know where they came from, so kept them around "just in case", but I think we can consider all cases cold at this point.
