### ISSUE TITLE
missing media?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/bostonlocaltv#223]
@Muraszko / @sroosa : These records are missing either their jpg or their mp4. If there's anything I should do, let me know? (note that the mlamedia01 links won't work because it does a referer check.)

http://bostonlocaltv.org/catalog/2394_09581_2
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_09851_2.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_09851_2_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_09581_3
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_09851_3.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_09851_3_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_09581_4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_09851_4.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_09851_4_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_09581_5
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_09851_5.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_09851_5_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_09581_6
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_09851_6.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_09851_6_thumbnail.jpg

http://bostonlocaltv.org/catalog/72394_09581_6
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_09851_7.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_09851_7_thumbnail.jpg

http://bostonlocaltv.org/catalog/72394_09581_8
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_09851_8.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_09851_8_thumbnail.jpg

http://bostonlocaltv.org/catalog/72394_09581_9
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_09851_9.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_09851_9_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_10406_2
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_10406_2..mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_10406_2._thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_10406_6
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_10406_6_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11424_2
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11424_2_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11424_3
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11424_3_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11424_4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11424_4_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11766_2
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_11776_2.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11776_2_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11766_3
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_11776_3.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11776_3_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11766_4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_11776_4.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11776_4_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11766_5
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_11776_5.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11776_5_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11766_6
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_11776_6.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11776_6_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11766_7
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2394_11776_7.mp4
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11776_7_thumbnail.jpg

http://bostonlocaltv.org/catalog/2639_0061_8
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/videos/2639_0061_8..mp4

http://bostonlocaltv.org/catalog/BPL_BK6NXAM8PZEACHN
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/whdh/images/14_BPL_BK6NXAM8PZEACHN_thumbnail.jpg

http://bostonlocaltv.org/catalog/BPL_HALP7T3M2C2GHZA
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/whdh/images/200_BPL_HALP7T3M2C2GHZA_thumbnail.jpg

http://bostonlocaltv.org/catalog/2394_11424
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/wcvb/images/2394_11424_1_thumbnail.jpg

http://bostonlocaltv.org/catalog/BPL_MKZS1YAO3JA6F63
MISSING: http://mlamedia01.wgbh.org/bostonlocaltv/whdh/images/222_BPL_MKZS1YAO3JA6F63_thumbnail.jpg

**Comment by sroosa** [comment]
@mccalluc and @Muraszko: I figured them all out! So most of them were an error in the filename in the pbcore. Those have all been fixed, and I exported the pbcore for those records, which we can reingest into the site and fix those. The other things were thumbnails that actually were missing. They never got created. I created them, and can either put them up on mlamedia01 or S3, wherever we're putting them. Or I can send all of this to Chuck and he can do the ingesting and uploading, which might be best if there is some file renaming happening. Let me know which way to proceed.

**Comment by Muraszko** [comment]
Cool, thanks Sadie.  I think it's probably best if we just got a complete export of the entire PBCore Collection they fall under because the records are not split individually, then we just replace the current export on S3.

**Comment by Muraszko** [comment]
@mccalluc @sroosa 
Noticing some more missing thumbs and videos on bostonlocaltv.wgbh-mla.org
I guess these files are not on S3, or they were not renamed to identifiers?

V_GOMVH1RTSRIM6L6
V_RNKW6IB07LTBCWX
V_OU08SK2E6HPIN3A
V_AHEUZH4NYM2YKXA

**Comment by sroosa** [comment]
@Muraszko @mccalluc: All of the videos and thumbs for those 4 records are on mlamedia01. So if they're not on S3 they should be easy to get over there.

**Comment by sroosa** [comment]
@mccalluc : Do you know the reason some of the videos and thumbs on mlamedia01, didn't make it over to S3 in their renamed form? Or will it take some investigation?

**Comment by mccalluc** [comment]
(Sadie will move a few more thumbs over, and then I will do an inventory to see what, if anything, is still missing.)

**Comment by mccalluc** [comment]
Ok, after just staring at the screen for a while, trying to sort out discrepancies, decided it'd be easier to just to do it from scratch. So that process is running as I type this, and now there's a script, should it every need to be done again.

**Comment by mccalluc** [comment]
I think it's working now.
