### ISSUE TITLE
Why are the item counts different?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/bostonlocaltv#244]
http://bostonlocaltv.wgbh-mla.org/catalog?search_field=all_fields -> 759
http://bostonlocaltv.org/catalog?search_field=all_fields -> 1631

Why the discrepancy? @sroosa : Maybe the XML you gave me doesn't have everything? Or maybe some records in the XML aren't being ingested?

**Comment by sroosa** [comment]
@mccalluc: I compared the counts for each collection, and it's definitely only a problem affecting the data from the WGBH database. In the database, it has the correct number of items marked as digitized and with the filenames. I just did a new export and as far as I can tell that export and the export I sent you are the same. Both pbcoreCollections have 906 counts of the element that I think is the one that indicates if something is digitized 
<pbcoreIdentifier source="Digital_Filename">barcode63017</pbcoreIdentifier>

Knowing that the data looks right (at least I assume that's how the data is supposed to look...?), I'm assuming it's something to do with how it's being ingested. Is that something you can look into? Do you need more from me on this?

**Comment by mccalluc** [comment]
One of the WGBH items (V_FJODRM5UW3YLW0Z) is failing on ingest, because one of the fields (description_s) is too large: 
> bytes can be at most 32766 in length; got 34651

I guess the version of solr we're using has changed, and maybe that's where the error is coming from?

**Comment by sroosa** [comment]
@mccalluc : If this is too big of a problem to solve right now, and we just need shorter fields, then you could tell me which records have fields that are too long and I could shorten them. Don't want this to block everything else, unless it's something that's super important beyond this situation.
