### ISSUE TITLE
Age the logs

### ISSUE THREAD

**Issue by afred** [WGBH/bostonlocaltv#269]
**done when** logs are aged to prevent filling disk.

**Comment by jasoncorum** [comment]
@afred: I haven't done much with log rotation in my past. How does this approach sound to you? https://gorails.com/guides/rotating-rails-production-logs-with-logrotate

**Comment by afred** [comment]
@jasoncorum I implemented a Rails based solution for AAPB, but I think using logrotate is more flexible, and cleaner.

However, it does mean that the Rails app won't be responsible for managing it's own log aging. Which is fine, it just means that changes will probably go into https://github.com/WGBH/bostonlocaltv_deploy instead

**Comment by jasoncorum** [comment]
@afred @Muraszko  I have this set up locally in my bostonlocaltv_deploy repo, but I don't have access to push my branch to Github. Could you grant me access? Thanks!

**Comment by afred** [comment]
Ha, i don't either. @Muraszko? Otherwise we'll need to ask Chuck.

**Comment by jasoncorum** [comment]
Closing this one since the code was merged on deploy
