### ISSUE TITLE
Bostonlocaltv.org is down

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/bostonlocaltv#278]
I received an HTTP 503 error when trying to access bostonlocaltv.org this morning. The message states:

The bostonlocaltv.org page isn’t working

bostonlocaltv.org is currently unable to handle this request.

This is high priority

**Comment by jasoncorum** [comment]
@caseyedavis12 @afred - I ran the Blacklight rake task to clear out old searches and the site appears to be back up. We have a cron task in the deploy repo that should set this up to run nightly. I checked the crontab and nothing was defined, so I don't think we've run a deploy here, yet, with the new code. I'll touch base with @afred to make sure we get this out in the wild.
