### ISSUE TITLE
add a representation of digitization workflow to docs in github wiki

### ISSUE THREAD

**Issue by afred** [WGBH/bostonlocaltv#96]
![image](https://f.cloud.github.com/assets/1507490/2117991/8443c9f6-90ed-11e3-9eb0-2a71064e2b7f.png)

**Comment by mccalluc** [comment]
I've purged the digitization request machinery, along with all the other RDB stuff, so this is no longer relevant.

**Comment by afred** [comment]
@mccalluc @sroosa @Muraszko Does this diagram still have value? Will we want to implement something like this in the future, putting more effort into usability, and design, to where it might actually be effective?
